spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 4ebf3974dccb48b3d811
            clientSecret: 4d6e5feff24a1f1bf3873f23bf0eb052bbfe7346
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create